### ISSUE TITLE
Add code coverage to CI

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PyVertical#27]
## Description
Add codecoverage report to CI

## Type of Test
- [ ] **Unit test** (e.g. checking a loop, method, or function is working as intended)
- [ ] **Integration test** (e.g. checking if a certain group or set of functionality is working as intended)
- [ ] **Regression test** (e.g. checking if by adding or removing a module of code allows other systems to continue to function as intended)
- [ ] **Stress test** (e.g. checking to see how well a system performs under various situations, including heavy usage)
- [ ] **Performance test** (e.g. checking to see how efficient a system is as performing the intended task)
- [X] Other...

## Expected Behavior
A code coverage step in the test script.
Each PR should generate a report on code coverage.
If coverage goes below 95%, the build should fail

## Additional Context
See the [PySyft test script](https://github.com/OpenMined/PySyft/blob/master/.github/workflows/tests.yml#L73)

**Comment by pavlos-p** [comment]
@TTitcombe Should we leave this Closed for now, since it has been removed from #23 and re-implement it in the future?
