### ISSUE TITLE
Find EHR dataset

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PyVertical#40]
## Question
Find an Electronic Health Record (EHR) dataset for use in the next stage of PyVertical

## Further Information
In the next stage of PyVertical, we will apply the concept to a dataset more complex than MNIST.
To demonstrate the utility of the technology, it would be useful to use a dataset with obvious links to real-world applications, yet still simple enough that we can quickly develop a useful product.

It was decided to use EHR data. Some possibilities are:
- [MIMIC](https://mimic.physionet.org/)
    - Need to apply for access
- [Synthetic data](https://synthetichealth.github.io/synthea/)

All suggestions are welcome

**Comment by EXYNOS-999** [comment]
https://docs.google.com/document/d/1xD9xFJpXkDwFKm0cNZ_kxnOygXDwybiTLH9VIetFQ10/edit?usp=sharing

**Comment by TTitcombe** [comment]
Thanks for the input @EXYNOS-999. I think we'll go with Synthea: not requiring users to sign a license to use PyVertical is a huge benefit
