### ISSUE TITLE
Bazel builds failing

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PyVertical#42]
## Description
The bazel build stage of the test script is failing. See https://github.com/OpenMined/PyVertical/pull/39/checks?check_run_id=851670305 and https://github.com/OpenMined/PyVertical/runs/851664851?check_suite_focus=true

Multiple PRs are failing, and one of the PRs had previously passed the bazel build stage on an earlier day, so it looks like this is caused by an upstream change. Investigate whether or not we can do anything about it.

I have successfully built locally on Ubuntu 18.04, Python 3.7. Perhaps it's an issue with github CI's bazel?

## How to Reproduce
1. Look at failing CI tests on PRs

## Expected Behavior
The builds pass

## Screenshots
NA

## System Information
 - OS: Ubuntu
 - OS Version: 18.04
 - Language Version: Python 3.6, 3.7, 3.8

**Comment by EssieYee** [comment]
Excuse me, i have alsp got some problems in running build-psi.sh, do you know how to fix it? Thanks.

INFO: Repository rule 'org_openmined_psi' returned: {"remote": "https://github.com/OpenMined/PSI", "commit": "ca2866e3c70a018ed9a5a2e7af5bcbd31dc49df9", "shallow_since": "2020-14-07", "init_submodules": True, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "org_openmined_psi"}
ERROR: /home/tanghengzhu/.cache/bazel/_bazel_tanghengzhu/9b06aa84c50b71eaea609540d6aa319b/external/org_openmined_psi/private_set_intersection/javascript/toolchain/cc_toolchain_config.bzl:171:17: name '**CcToolchainConfigInfo' is not defined**
ERROR: error loading package '': Extension 'private_set_intersection/javascript/toolchain/cc_toolchain_config.bzl' has errors
ERROR: error loading package **'': Extension 'private_set_intersection/javascript/toolchain/cc_toolchain_config.bzl' has errors**
INFO: Elapsed time: 8.584s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
