### ISSUE TITLE
Add Windows and MacOS tests

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PyVertical#43]
## Description
Add test builds on Windows and MacOS. PyVertical involves a code compilation step (PSI) which varies system to system, so it is important we test all common OSs to catch bugs.

To save time, only test Python 3.7 on each new OS

## Type of Test
- [X] **Unit test** (e.g. checking a loop, method, or function is working as intended)
- [ ] **Integration test** (e.g. checking if a certain group or set of functionality is working as intended)
- [ ] **Regression test** (e.g. checking if by adding or removing a module of code allows other systems to continue to function as intended)
- [ ] **Stress test** (e.g. checking to see how well a system performs under various situations, including heavy usage)
- [ ] **Performance test** (e.g. checking to see how efficient a system is as performing the intended task)
- [ ] Other...

## Expected Behavior
Opening a PR should run tests on:
- Ubuntu 18.04
    - Python 3.6, 3.7, 3.8 (current behaviour)
- Windows (latest version available on github CI)
    - Python 3.7
- MacOS (latest version available on github CI)
    - Python 3.7

**Comment by ramesht007** [comment]
Hey, @TTitcombe I would like to work on this issue🙂

**Comment by TTitcombe** [comment]
@ramesht007 Sorry, I should have removed the available label. I do have a PR open for this (#53) but it's blocked by an upstream error. Thanks for the offer, though!

**Comment by ramesht007** [comment]
No issues
