### ISSUE TITLE
Train Model on Synthea data

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PyVertical#70]
## Feature Description
Train a machine learning model (not a split network) on synthea data to solve some task.
Create a notebook which demonstrates the performance of this model.

Synthea data can be fairly large, so we should find the minimum number of patients we need to develop a useful model. We're just trying to demonstrate a concept, not cure a disease.

## Is your feature request related to a problem?
Before we attempt to develop a model on vertically-partitioned synthea data, we should confirm that a model can be trained successfully.

This model will also set the baseline so we can compare performance drop caused by privacy-preserving vertical federated learning

## What alternatives have you considered?
None

## Additional Context
An existing solution we could use is diabetes prediction https://github.com/IBM/example-health-machine-learning/blob/master/diabetes-prediction.ipynb

Requires  #58 to be complete

**Comment by abbas5253** [comment]
Hey @TTitcombe , Please assign this to me.
