### ISSUE TITLE
documents and source code not match

### ISSUE THREAD

**Issue by tanjuntao** [OpenMined/PyVertical#72]
## Description
The code in `PyVertical/examples/PyVertical Example.ipynb` were outdated, since it called a function `compute_psi`, which is shown to be deprecated in `src/psi/util.py`.

**Comment by TTitcombe** [comment]
Hi @tanjuntao, thanks for trying out PyVertical.

This issue is fixed in this PR https://github.com/OpenMined/PyVertical/pull/60, which we hope to merge soon

**Comment by tanjuntao** [comment]
That's great!

**Comment by pavlos-p** [comment]
I am closing this issue since it has been solved in PR #60 .
