### ISSUE TITLE
PSI builds failing 

### ISSUE THREAD

**Issue by EssieYee** [OpenMined/PyVertical#75]
## Description
I have got some problems in running build-psi.sh. The ERROR infomation is as follows:

INFO: Repository rule 'org_openmined_psi' returned: {"remote": "https://github.com/OpenMined/PSI", "commit": "ca2866e3c70a018ed9a5a2e7af5bcbd31dc49df9", "shallow_since": "2020-14-07", "init_submodules": True, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "org_openmined_psi"}
ERROR: /home/tanghengzhu/.cache/bazel/_bazel_tanghengzhu/9b06aa84c50b71eaea609540d6aa319b/external/org_openmined_psi/private_set_intersection/javascript/toolchain/cc_toolchain_config.bzl:171:17: **name 'CcToolchainConfigInfo' is not defined**
ERROR: error loading package '': Extension 'private_set_intersection/javascript/toolchain/cc_toolchain_config.bzl' has errors
ERROR: error loading package '': **Extension 'private_set_intersection/javascript/toolchain/cc_toolchain_config.bz**l' has errors
INFO: Elapsed time: 8.584s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

## How to Reproduce
1. Installed bazel
2. run the build script with .github/workflows/scripts/build-psi.sh..'

## Expected Behavior
This should generate a _psi_bindings.so file and place it in src/psi/.

## System Information
 - OS Version: Linux sigmaster 3.10.0  Red Hat 4.8.5-39
 - Language Version: python 3.7.8
 - Package Manager Version: Conda 4.6.14
 - Bazel Version: 1.0.0 (3.7.1 is also tried)

**Comment by TTitcombe** [comment]
Hi @EssieYee. I will take a look at this, but I think it might be an issue with the PSI library, which is an upstream dependency from this repo. Would you like to also open an issue in https://github.com/OpenMined/PSI? I will leave this issue open for the meantime for reference purposes

If you would like to try PyVertical while this issue is being fixed, we do have a Docker image

**Comment by EssieYee** [comment]
OK, thanks a lot!

**Comment by TTitcombe** [comment]
Hi @EssieYee , it looks like the issue has been fixed on the PSI side, is that correct?
https://github.com/OpenMined/PSI/issues/101

**Comment by EssieYee** [comment]
@TTitcombe  Yes, the issue has been fixed. Thanks for your help, and it can be closed now.
